name: Test Automation

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Create reports directory and sample file
      run: |
        mkdir -p reports
        echo "Test report" > reports/test.txt
        ls -la reports/
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: reports/ 